### ISSUE TITLE
Set up Rails repo

### ISSUE THREAD

**Issue by Stivaros** [Synergise/learning-journal#2]
- [x] Spin up new rails 6.0.3 application with psql as DB, no minitest, turbolinks or spring. 

Add and install:

- [x] Devise 

Test group:
- [x] RSpec-rails
- [x] FactoryBot
- [x] Database_cleaner (check if we still need for rails 6 apps?)
- [x] Capybara
- [x] Webdrivers
- [x] Faker

Development:
- [x] Rubocop

(Any other gems you think we need?)

**Comment by jasylwong** [comment]
> * [x]  Spin up new rails 6.0.3 application with psql as DB, no minitest, turbolinks or spring.
> 
> Add and install:
> 
> * [x]  Devise
> 
> Test group:
> 
> * [x]  RSpec-rails
> * [x]  FactoryBot
> * [x]  Database_cleaner (check if we still need for rails 6 apps?)
> * [x]  Capybara
> * [x]  Webdrivers
> * [x]  Faker
> 
> Development:
> 
> * [x]  Rubocop
> 
> (Any other gems you think we need?)

**Comment by jasylwong** [comment]
Active record?
SimpleCov?

**Comment by Stivaros** [comment]
ActiveRecord comes with Rails: https://github.com/Synergise/learning-journal/blob/setup_rails/Gemfile.lock#L45

SimpleCov we can do alongside the CodeClimate setup in #3

**Comment by jasylwong** [comment]
Closed, as PR has been reviewed (ES) and merged (JW).
